name: compilar y publica

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with: 
        node-version: '18'

    - name: instalar dependencias
      run: npm ci
      
    - name: crear proyecto
      run: npm run build
      

    
 - name: Deploy project
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages
